### ISSUE TITLE
remove sensitive data

### ISSUE THREAD

**Issue by danielmichaels** [A-Wheeto/Dashboard#1]
Great project, well done!

While you may (or may not) be using a free account on OpenWeatherMap, its still a good idea to not commit sensitive data to your public repository. 

https://github.com/A-Wheeto/Dashboard/blob/fdefae2e5980af3c9fb351f6dbc3b6eda2d84bc7/venv/Scripts/weather2.py#L10

Happy to help if you need some guidance on this.

**Comment by A-Wheeto** [comment]
Thank you Daniel, I'm new to Github and it didn't occur to me I would need to omit some data in the code. What's the best way to do this?

**Comment by A-Wheeto** [comment]
Removed API keys from weather2.py and news.py

**Comment by danielmichaels** [comment]
No worries, it's cool - we've all done it!

As for ways around this, I would look at two options:

- Environment variables
- Using a `.env` (or similar) file to store the keys. You then add this file to your `.gitignore` so it doesn't get added.

There are a lot of other options but using Environment variables is probably most common. Something like this would work.

```sh
# in your terminal
export OWM_KEY=abc123 # windows is different, I think its 'set'
```

To access the key from python, use the `os` module.

```python
import os
import requests

OWM_KEY = os.getenv('OWM_KEY', None) # sets None as default if not found
# OWM_KEY = os.environ.get('OWM_KEY') # raises exception if not found

url = f'https://api.openweathermap.org/data/2.5/onecall?lat=53.9600&lon=1.0873&units=metric&appid={OWM_KEY}'
resp = requests.get(url)
resp.json()
# etc..
```

Hopefully that helps a little. I would also regenerate your old tokens as its possible for someone to look through your commits and pull out the keys from there.

**Comment by A-Wheeto** [comment]
Excellent advice thank you Daniel! I'll get them setup in Environmental Variables.

**Comment by danielmichaels** [comment]
:+1:  feel free to close this whenever you're ready. Glad I could help.

**Comment by A-Wheeto** [comment]
Removed API tokens from weather2.py and news.py.
