### ISSUE TITLE
Congrats for getting listed in Python Weekly

### ISSUE THREAD

**Issue by PySimpleGUI** [A-Wheeto/Dashboard#3]
Congratulations.... saw your project listed in the PythonWeekly.com email...

![image](https://user-images.githubusercontent.com/46163555/84441129-3b6e7800-ac09-11ea-9d05-59b1c2c1c10e.png)

**Comment by A-Wheeto** [comment]
Wow that's amazing! Thanks for showing me this :)

**Comment by PySimpleGUI** [comment]
Told you that you had a good idea with your layout!   Others seem to have agreed.
